### PR TITLE
feat: capture trusted-proxy device pairing state in DetectResult.meta

### LINKED ISSUE #3885: [obs-gap:openclaw] OpenClaw: trusted-proxy device pairing/auto-approval state not captured
Automated harness-observability audit found a gap for **openclaw**.

- **Harness exposes:** Devices (Control UI, WebChat) can now be auto-approved from allowlisted trusted-proxy identities with non-admin scope caps, distinct from manual existing-device upgrades.
- **ClawMetry misses:** The adapter has no signal for paired/approved devices, their scope caps, or which were auto- vs manually-approved — nothing under DetectResult.meta or Session.extra tracks device pairing state.
- **Where (harness):** `CHANGELOG.md (Unreleased): 'Trusted-proxy browser pairing' entry`
- **Severity:** medium
- **Closest capability:** new

_Filed by `scripts/harness/audit.py`. Fingerprint: hgap-4fb01a70db (used to dedupe — keep it in the body)._

### PR DESCRIPTION
**Pull request by vivekchand**
Closes #3885

## Summary
- Adds `_gateway_trusted_proxy_devices()` to `clawmetry/adapters/openclaw.py`, following the identical pattern of `_gateway_plugin_health()` and `_gateway_host_status()`
- Calls `gateway.status` RPC first, then falls back to a dedicated `gateway.devices` RPC, extracting paired device list, per-device scope caps, and auto- vs manual-approval flag
- Merges `gatewayTrustedProxyDevices` and `gatewayTrustedProxyDeviceSummary` into `DetectResult.meta`; data flows automatically to `GET /api/agents/openclaw` via the existing `to_dict()` path

## Test plan
- Import check passes: `from clawmetry.adapters.openclaw import _gateway_trusted_proxy_devices` ✓
- Function returns `{}` gracefully when no gateway RPC is available (no `_gw_ws_rpc` attr → early return) ✓
- No lint errors introduced in the changed file ✓
- On older gateway installs that don't expose device keys the function is a silent no-op; on installs that do, `meta["gatewayTrustedProxyDevices"]` will be populated automatically

---
_Generated by [Claude Code](https://claude.ai/code/session_01A1RDrs6ZytZs8Wpo1ZjjD1)_

### CODE REVIEW

**Comment by vivekchand** [comment]
**Blocker: C6 branch-protection config gap — not a code issue**

All CI checks pass (lint, tests, E2E, install, etc.). The only failure is `C6 Required-status-checks gate`, a meta-check that verifies these four checks are marked **required** in branch protection for `main` — they are not yet:

- `OSS golden path (wheel + OpenClaw + 9 tabs)`
- `Cross-repo handoff (C4)`
- `MOAT Keystone (13-endpoint bar)`
- `E2E Browser Tests (critical subset)`

**To unblock (owner action required, ~30 s):**

Option A — Browser:
> Settings → Branches → Edit `main` → Require status checks → add the four names above → Save

Option B — Terminal:
```bash
bash scripts/close-c6.sh
```

Option C — Actions (no local clone needed):
> Actions → "Apply required E2E status checks (C6 -- one-shot)" → Run workflow → `confirm=APPLY`, paste a fine-grained PAT with Administration read+write on the three repos

Once those checks are required on `main`, this PR is immediately mergeable — no code changes needed.

---
_Auto-mergeability sweep — skipping: requires repo admin to configure branch protection (C6)_

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by vivekchand** [comment]
**Automated PR health sweep — 2026-07-21**

All code CI checks are now green on the current branch head (`df0087d`). Here's what happened and what's still needed:

---

### Root cause of prior CI failures
Commit `60c3aea` ("fix: resolve merge conflict with #3891 presence roster") accidentally **emptied `clawmetry/adapters/openclaw.py`** during conflict resolution (the file was set to the empty blob `e69de29`). This caused the `ImportError: cannot import name 'OpenClawAdapter'` across all CI jobs.

Commit `df0087d` (already pushed) restored the file correctly and is now the branch head.

---

### Current CI status (on `df0087d`)
| Check | Status |
|---|---|
| Syntax & Lint | ✅ pass |
| PR build | ✅ pass |
| Install + boot + health-check | ✅ pass |
| API Tests (ubuntu ×2, windows, macos) | ✅ all pass |
| pip install (ubuntu, windows, macos) | ✅ all pass |
| Wheel install & asset presence | ✅ pass |
| E2E Browser Tests (critical subset) | ✅ pass |
| OSS golden path (wheel + OpenClaw + 9 tabs) | ✅ pass |
| Live OpenClaw E2E | ✅ pass |
| MOAT Verifier (72 tests) | ✅ pass |
| MOAT Keystone (13-endpoint bar) | ✅ pass |
| Cross-repo handoff (C4) | ✅ pass |
| Eval Suite Gate | ✅ pass |
| Compression Safety Eval | ✅ pass |
| **C6 Required-status-checks gate** | ❌ fail — needs admin action (not a code issue) |

---

### Remaining blocker: C6 gate (one-time repo setup)
Branch protection on `main` doesn't yet list the E2E checks as required. Fix via GitHub Settings UI (~60 s):

1. `github.com/vivekchand/clawmetry/settings/branches` → Edit `main` → Require status checks → add:
   - `OSS golden path (wheel + OpenClaw + 9 tabs)`
   - `Cross-repo handoff (C4)`
   - `MOAT Keystone (13-endpoint bar)`
   - `E2E Browser Tests (critical subset)`
2. Same for `clawmetry-cloud`: add `Cloud golden-path browser E2E`
3. Same for `clawmetry-landing`: add `Landing golden path (C3)`

Or run the one-shot workflow: **Actions → "Apply required E2E status checks (C6 -- one-shot)"** with a fine-grained PAT (Administration: write on all 3 repos).

Once C6 is configured, this PR is ready to merge.


---
_Generated by [Claude Code](https://claude.ai/code)_
